version: '3'

services:
  php:
       build:
          context: .
          dockerfile: Dockerfile
       ports:
	    - "3000:80"
       depends_on:
	    - "db"
       volumes:
	    - ./docker/www:/var/www/html
 
  db:
       image: mysql
       restart: always
       command: mysqld --default-authentication-plugin=mysql_native_password
       environment:
	    MYSQL_ROOT_PASSWORD: root
	    MYSQL_DATABASE: test_db
	    MYSQL_USER: test
	    MYSQL_PASSWORD: test
	    MYSQL_ROOT_HOST: "%"
       volumes:
             - ./docker/db:/var/lib/mysql
       ports: 
             - "3306:3306"
		
   adminer:
       image: adminer
       ports:
            - "8080:8080"
       depends_on:
            - "db"
		
networks:
    db:
        driver: bridge
